TotalArr = [
        {
            "questionid": 1232,
            "optionid": 1904,
            "optiontitle": "未在校",
            "question_sort": 0,
            "question_type": 1,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "answered": True
        },
        {
            "questionid": 1233,
            "optionid": 0,
            "optiontitle": 0,
            "question_sort": 0,
            "question_type": 7,
            "option_sort": 0,
            "range_value": "",
            "content": "四川省成都市",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        },
        {
            "questionid": 1234,
            "optionid": 0,
            "optiontitle": 0,
            "question_sort": 0,
            "question_type": 4,
            "option_sort": 0,
            "range_value": "",
            "content": "在家",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        },
        {
            "questionid": 1235,
            "optionid": "1906",
            "optiontitle": "未接触过",
            "question_sort": 0,
            "question_type": 1,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        },
        {
            "questionid": 1236,
            "optionid": "1907",
            "optiontitle": "没有出现症状",
            "question_sort": 0,
            "question_type": 2,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        },
        {
            "questionid": 1237,
            "optionid": "1913",
            "optiontitle": "否，身体健康",
            "question_sort": 0,
            "question_type": 1,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        },
        {
            "questionid": 1238,
            "optionid": 0,
            "optiontitle": 0,
            "question_sort": 0,
            "question_type": 3,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        },
        {
            "questionid": 1239,
            "optionid": 0,
            "optiontitle": 0,
            "question_sort": 0,
            "question_type": 3,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        },
        {
            "questionid": 1240,
            "optionid": 0,
            "optiontitle": 0,
            "question_sort": 0,
            "question_type": 3,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        },
        {
            "questionid": 1241,
            "optionid": "1918",
            "optiontitle": "是",
            "question_sort": 0,
            "question_type": 1,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        }
]
