Postdates = {
    "name": None,
    "password": None,
    "school": {
        "search_pinyin": ".scqhgdx.sichuanqinghuagongdaxue.sichuanqinghuagongdaixue.",
        "school_num": "",
        "name": "四川轻化工大学",
        "domain": "suse",
        "pinyin": "sichuanqinghuagongdaxue",
        "and_umeng_app_key": "55d19d74e0f55a02960038a5",
        "and_umeng_app_secret": "6f2ac4756ebc4dfbb1ca8893125a67b8",
        "ios_umeng_app_key": "55d19e7667e58e182b001a19",
        "ios_umeng_app_secret": "qx0crqzhadgruicjcs2dxqfjqrg8fjjb",
        "config_update_time": "2020-07-24 10:22:51",
        "offset_map_x": "104.771668",
        "offset_map_y": "29.338200",
        "ex_field": {
            "school_top_flag": "schoollogo",
            "school_top_url": {
                "default": {"img": "null", "words": ""},
                "schoollogo": {
                    "img": "http://store.weishao.com.cn//group1/M00/20/05/rBGLH14-ZFeAcByqAAG80V5l0w0802.png",
                    "words": "四川轻化工大学"},
                "customer": {"img": "", "words": ""}
            }
        },
        "configLoaded": True,
        "config": {
            "app_url": "null",
            "offset_map_x": "104.771668",
            "offset_map_y": "29.338200",
            "is_scores": "0",
            "search_pinyin": ".scqhgdx.sichuanqinghuagongdaxue.sichuanqinghuagongdaixue.",
            "school_num": "",
            "name": "四川轻化工大学",
            "domain": "suse",
            "pinyin": "sichuanqinghuagongdaxue",
            "url_crash_upload": "http://172.16.56.175/report/?mod",
            "url_download": "http://store.weishao.com.cn/",
            "url_main_server": "https://service.weishao.com.cn/whistlenew/index.php",
            "url_upload": "http://store.weishao.com.cn//image/upload2",
            "and_umeng_app_key": "55d19d74e0f55a02960038a5",
            "and_umeng_app_secret": "6f2ac4756ebc4dfbb1ca8893125a67b8",
            "ios_umeng_app_key": "55d19e7667e58e182b001a19",
            "ios_umeng_app_secret": "qx0crqzhadgruicjcs2dxqfjqrg8fjjb",
            "config_update_time": "2020-07-24 10:22:51",
            "memo": " * ",
            "api_server": "http://lightapp.weishao.com.cn/linkshare/NewsClient.do?",
            "QRUrl": "http://login.weishao.com.cn/index.html?ver=1",
            "icon_url": "http://store.weishao.com.cn//group1/M00/20/05/rBGLH14-ZFeAcByqAAG80V5l0w0802.png",
            "campuscard_bgd_img": "",
            "disclaimer": {},
            "memo_ex": "null",
            "campuscard_bgd_img_new": {},
            "ex_field": {
                "school_top_flag": "schoollogo",
                "school_top_url": {
                    "default": {"img": "null", "words": ""},
                    "schoollogo": {
                        "img": "http://store.weishao.com.cn//group1/M00/20/05/rBGLH14-ZFeAcByqAAG80V5l0w0802.png",
                        "words": "四川轻化工大学"},
                    "customer": {"img": "", "words": ""}
                }
            },
            "customized": "0",
            "client_config": "{\"web_config\":{\"basicConfig\":{\"color\":\"#0dac67\"},\"imgUrlKeys\":[{"
                             "\"text\":\"logo_icon\"}]}}",
            "app_cfg": {
                "version_url": "https://cms.weishao.com.cn/versions/",
                "cloudGround_status": 1,
                "bind_tell": "null",
                "bind_mail": "null",
                "user_center": "null",
                "protocol_url": "https://cms.weishao.com.cn/agreements/",
                "password_change": "null",
                "reset_pwd_url": 1,
                "account_security_url": 1,
                "login_bind": 1,
                "module_array": [["userInfo", "accountSafe", "schoolCard", "about", "feedback", "setting", "contacts"]],
                "module_name": [["", "", "", "", "", "", ""]],
                "module_name_en": [["", "", "", "", "", "", ""]],
                "password_url": "null",
                "bind_phone_url": "https://xiaoyuan.weishao.com.cn/weishao/plain?"
            },
            "uploadurl_hx": "https://download.weishao.com.cn/uploadfile",
            "uploadurl_overtime": 180,
            "originalDomain": "suse"
        }
    }
}

Answer = {
    "sch_code": "suse",
    "stu_code": None,
    "stu_name": None,
    "identity": None,
    "path": None,
    "organization": None,
    "gender": None,
    "activityid": "102",
    "anonymous": 0,
    "canrepeat": 1,
    "repeat_range": 1,
    "question_data": None,
    "totalArr": None,
    "private_id": 0
}

TotalArr = [
        {
            "questionid": 1232,
            "optionid": 1903,
            "optiontitle": "在校",
            "question_sort": 0,
            "question_type": 1,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "answered": True
        },
        {
            "questionid": 1233,
            "optionid": 0,
            "optiontitle": 0,
            "question_sort": 0,
            "question_type": 7,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": "",
            "answerid": 0,
            "hide": True,
            "answered": False
        },
        {
            "questionid": 1234,
            "optionid": 0,
            "optiontitle": 0,
            "question_sort": 0,
            "question_type": 4,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": "",
            "answerid": 0,
            "hide": True,
            "answered": False
        },
        {
            "questionid": 1235,
            "optionid": 0,
            "optiontitle": 0,
            "question_sort": 0,
            "question_type": 1,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "answerid": 0,
            "hide": True,
            "answered": False
        },
        {
            "questionid": 1236,
            "optionid": "1907",
            "optiontitle": "没有出现症状",
            "question_sort": 0,
            "question_type": 2,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        },
        {
            "questionid": 1237,
            "optionid": "1913",
            "optiontitle": "否，身体健康",
            "question_sort": 0,
            "question_type": 1,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        },
        {
            "questionid": 1238,
            "optionid": 0,
            "optiontitle": 0,
            "question_sort": 0,
            "question_type": 3,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        },
        {
            "questionid": 1239,
            "optionid": 0,
            "optiontitle": 0,
            "question_sort": 0,
            "question_type": 3,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        },
        {
            "questionid": 1240,
            "optionid": 0,
            "optiontitle": 0,
            "question_sort": 0,
            "question_type": 3,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        },
        {
            "questionid": 1241,
            "optionid": 1918,
            "optiontitle": "是",
            "question_sort": 0,
            "question_type": 1,
            "option_sort": 0,
            "range_value": "",
            "content": "",
            "isotheroption": 0,
            "otheroption_content": "",
            "isanswered": True,
            "answerid": 0,
            "hide": False,
            "answered": True
        }
    ]
